# Generated by Django 5.0.6 on 2024-08-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rosw3ll_portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
    ]
